### PR TITLE
Cylinder generator

### PR DESCRIPTION
**Pull request by toji**
Does what it says on the label :)

### CODE REVIEW

**Comment by donny-dont** [comment]
Awesome! One quick thing I noticed after I merged the sphere generator and added some texturing stuff. It appears you aren't duplicating vertices at the seam. Might want to double check that with the cylinder as well.

texcoords

**Comment by toji** [comment]
Derp. Yeah, that would be a problem. And yeah, the cylinder will have the same issue. It'll be an easy fix though (and will simplify some of the logic too! Bonus!)

**Comment by donny-dont** [comment]
Do a pull and you'll have some more shaders to muck with. If the output looks weird make sure to modify the InputLayout elements to match whatever the shader came up with in terms of the attribute offset. I think I'm going to modify the ShaderProgram to expose a way to set the attribute indices directly.

**Comment by donny-dont** [comment]
Also is there any common code within the sphere and cylinder stuff?

For my MS I wrote a scene graph and supported sphere/cylinder/cone. http://shadegl.svn.sourceforge.net/viewvc/shadegl/SceneGraph/Meshes/. I had common code in a Quadratic base class. If I'm remembering right I think that I was basing things on how GLUT worked.

If that helps you feel free to crib from it.

**Comment by toji** [comment]
Okay, Cylinder should be in decent shape now. Confirmed that UVs are correct, and made the class a bit more robust while I was at it. (Fun fact: Cylinder can also function as a cone if you set the topRadius to 0!)

I'm working on correcting the Sphere UVs, but that'll be a different pull request. I'm also looking at a more general quadratic class, but for the moment it's easier to simply fix the Sphere and work with that.

[EDIT]: Oh, yeah! And I included a different testing texture in this patch. Hope you don't mind. The old one couldn't be tiled (NPOT) and didn't give clear indications which direction it was facing. The new one is much clearer.

**Comment by toji** [comment]
Rebased. Should merge cleanly now!

**Comment by donny-dont** [comment]
Another one bites the dust! Thanks again!

**Pull request merged**
